version: '3'

services:

  abes-esr-gitpuller:
    build: ./image/
    image: abesesr/gitpuller-docker:1.1.0
    container_name: abes-esr-gitpuller
    environment:
      GIT_AS_UID: 0
      GIT_AS_GID: 0
    volumes:
      - ./:/folder-to-git-pull/:rw
        #      - /home/gully/.ssh/id_rsa:/root/.ssh/id_rsa.orig
        #      - /home/gully/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub.orig
